### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by kiwisky** [ideamark/breadbot#1]
I got following errors when install
<pre>tzpyyd@jfsys-270:breadAI-master$ python setup.py install
Requirement already satisfied: Django>=1.10.5 in c:\users\tzpyyd\appdata\local\programs\python\python36-32\lib\site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: PyDbLite>=3.0.4 in c:\users\tzpyyd\appdata\local\programs\python\python36-32\lib\site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: PyYAML>=3.12 in c:\users\tzpyyd\appdata\local\programs\python\python36-32\lib\site-packages (from -r requirements.txt (line 3))
Requirement already satisfied: configobj>=5.0.5 in c:\users\tzpyyd\appdata\local\programs\python\python36-32\lib\site-packages (from -r requirements.txt (line 4))
Requirement already satisfied: pyaml>=16.12.2 in c:\users\tzpyyd\appdata\local\programs\python\python36-32\lib\site-packages (from -r requirements.txt (line 5))
Requirement already satisfied: flake8>=3.4.1 in c:\users\tzpyyd\appdata\local\programs\python\python36-32\lib\site-packages (from -r requirements.txt (line 6))
Requirement already satisfied: pymongo>=3.5.1 in c:\users\tzpyyd\appdata\local\programs\python\python36-32\lib\site-packages (from -r requirements.txt (line 7))
Requirement already satisfied: nltk>=3.2.5 in c:\users\tzpyyd\appdata\local\programs\python\python36-32\lib\site-packages (from -r requirements.txt (line 8))
Requirement already satisfied: pytz in c:\users\tzpyyd\appdata\local\programs\python\python36-32\lib\site-packages (from Django>=1.10.5->-r requirements.txt (line 1))
Requirement already satisfied: six in c:\users\tzpyyd\appdata\local\programs\python\python36-32\lib\site-packages (from configobj>=5.0.5->-r requirements.txt (line 4))
Requirement already satisfied: pycodestyle<2.4.0,>=2.0.0 in c:\users\tzpyyd\appdata\local\programs\python\python36-32\lib\site-packages (from flake8>=3.4.1->-r requirements.txt (line 6))
Requirement already satisfied: mccabe<0.7.0,>=0.6.0 in c:\users\tzpyyd\appdata\local\programs\python\python36-32\lib\site-packages (from flake8>=3.4.1->-r requirements.txt (line 6))
Requirement already satisfied: pyflakes<1.7.0,>=1.5.0 in c:\users\tzpyyd\appdata\local\programs\python\python36-32\lib\site-packages (from flake8>=3.4.1->-r requirements.txt (line 6))
ERROR:root:Error parsing
Traceback (most recent call last):
  File "C:\Users\tzpyyd\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pbr\core.py", line 111, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "C:\Users\tzpyyd\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pbr\util.py", line 249, in cfg_to_args
    pbr.hooks.setup_hook(config)
  File "C:\Users\tzpyyd\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pbr\hooks\__init__.py", line 25, in setup_hook
    metadata_config.run()
  File "C:\Users\tzpyyd\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pbr\hooks\base.py", line 27, in run
    self.hook()
  File "C:\Users\tzpyyd\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pbr\hooks\metadata.py", line 26, in hook
    self.config['name'], self.config.get('version', None))
  File "C:\Users\tzpyyd\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pbr\packaging.py", line 755, in get_version
    name=package_name))
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name breadbot was given, but was not able to be found.
error in setup command: Error parsing F:\csoftzilla\AIAutoReply\breadAI-master\setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name breadbot was given, but was not able to be found.</pre>

**Comment by uncle-mark** [comment]
Hi, Pal
    Bread Bot can not be installed on Windows system. Only Linux is supported.
    But you can modify Bread Bot source code to make it work on Windows, and I will be glad if you share the new code with me.

Regards,
Mark

**Comment by kiwisky** [comment]
Hi ideanmark
Thanks for reply!
Yes, I'm using the Cygwin to simulate Linux ENV on Windows. I export PBR_VERSION='3.1.1', and seems the issue fixed. And I also changed some codes, seems the installation succeeds.
<pre>tzpyyd@jfsys-270:breadAI-master$ python setup.py install
Requirement already satisfied: Django>=1.10.5 in c:\users\tzpyyd\appdata\local\programs\python\python36-32\lib\site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: PyDbLite>=3.0.4 in c:\users\tzpyyd\appdata\local\programs\python\python36-32\lib\site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: PyYAML>=3.12 in c:\users\tzpyyd\appdata\local\programs\python\python36-32\lib\site-packages (from -r requirements.txt (line 3))
Requirement already satisfied: configobj>=5.0.5 in c:\users\tzpyyd\appdata\local\programs\python\python36-32\lib\site-packages (from -r requirements.txt (line 4))
Requirement already satisfied: pyaml>=16.12.2 in c:\users\tzpyyd\appdata\local\programs\python\python36-32\lib\site-packages (from -r requirements.txt (line 5))
Requirement already satisfied: flake8>=3.4.1 in c:\users\tzpyyd\appdata\local\programs\python\python36-32\lib\site-packages (from -r requirements.txt (line 6))
Requirement already satisfied: pymongo>=3.5.1 in c:\users\tzpyyd\appdata\local\programs\python\python36-32\lib\site-packages (from -r requirements.txt (line 7))
Requirement already satisfied: nltk>=3.2.5 in c:\users\tzpyyd\appdata\local\programs\python\python36-32\lib\site-packages (from -r requirements.txt (line 8))
Requirement already satisfied: pytz in c:\users\tzpyyd\appdata\local\programs\python\python36-32\lib\site-packages (from Django>=1.10.5->-r requirements.txt (line 1))
Requirement already satisfied: six in c:\users\tzpyyd\appdata\local\programs\python\python36-32\lib\site-packages (from configobj>=5.0.5->-r requirements.txt (line 4))
Requirement already satisfied: mccabe<0.7.0,>=0.6.0 in c:\users\tzpyyd\appdata\local\programs\python\python36-32\lib\site-packages (from flake8>=3.4.1->-r requirements.txt (line 6))
Requirement already satisfied: pyflakes<1.7.0,>=1.5.0 in c:\users\tzpyyd\appdata\local\programs\python\python36-32\lib\site-packages (from flake8>=3.4.1->-r requirements.txt (line 6))
Requirement already satisfied: pycodestyle<2.4.0,>=2.0.0 in c:\users\tzpyyd\appdata\local\programs\python\python36-32\lib\site-packages (from flake8>=3.4.1->-r requirements.txt (line 6))
running install
[pbr] Generating AUTHORS
[pbr] AUTHORS complete (0.0s)
running build
running build_py
running egg_info
writing breadbot.egg-info\PKG-INFO
writing dependency_links to breadbot.egg-info\dependency_links.txt
writing requirements to breadbot.egg-info\requires.txt
writing top-level names to breadbot.egg-info\top_level.txt
[pbr] Reusing existing SOURCES.txt
running install_lib
running install_data
copying etc\bread.cfg -> C:\Users\tzpyyd\AppData\Local\Programs\Python\Python36-32\etc\
copying bin\breadbot -> C:\Users\tzpyyd\AppData\Local\Programs\Python\Python36-32\bin\
copying bin\breadbot~ -> C:\Users\tzpyyd\AppData\Local\Programs\Python\Python36-32\bin\
running install_egg_info
removing 'C:\Users\tzpyyd\AppData\Local\Programs\Python\Python36-32\Lib\site-packages\breadbot-3.1.1-py3.6.egg-info' (and everything under it)
Copying breadbot.egg-info to C:\Users\tzpyyd\AppData\Local\Programs\Python\Python36-32\Lib\site-packages\breadbot-3.1.1-py3.6.egg-info
running install_scripts
[Warning] No sec found

 All Complete!</pre>

**Comment by uncle-mark** [comment]
Glad to hear that :)

**Comment by kiwisky** [comment]
Hmm...The installation is not completed yet. I run MongoDB on windows and the installation failed again. This seems related to 'gbk' character set when insert data and I'm using Chinese.
<pre>...
insert F:\csoftzilla\AIAutoReply\breadAI-master\data\dia\person\atomic_yml...
insert F:\csoftzilla\AIAutoReply\breadAI-master\data\dia\person\bread_yml...
insert F:\csoftzilla\AIAutoReply\breadAI-master\data\dia\person\emotion_yml...
insert F:\csoftzilla\AIAutoReply\breadAI-master\data\dia\person\mark_yml...
insert F:\csoftzilla\AIAutoReply\breadAI-master\data\klg\computer_yml...
insert F:\csoftzilla\AIAutoReply\breadAI-master\data\klg\life_yml...
Traceback (most recent call last):
  File "F:\csoftzilla\AIAutoReply\breadAI-master\bin\breadbot", line 47, in <module>
    active(cmd)
  File "F:\csoftzilla\AIAutoReply\breadAI-master\bin\breadbot", line 33, in active
    core.data.insertData()
  File "C:\Users\tzpyyd\AppData\Local\Programs\Python\Python36-32\lib\site-packages\breadbot\core\data.py", line 22, in __init__
    self.insert_db_data(changedDataList)
  File "C:\Users\tzpyyd\AppData\Local\Programs\Python\Python36-32\lib\site-packages\breadbot\core\data.py", line 115, in insert_db_data
    readStr = self._read_data_file(dataPath)
  File "C:\Users\tzpyyd\AppData\Local\Programs\Python\Python36-32\lib\site-packages\breadbot\core\data.py", line 41, in _read_data_file
    readStr = f.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0x80 in position 5875: illegal multibyte sequence
</pre>

**Comment by uncle-mark** [comment]
Hi, Pal:
    Bread Bot was designed to support English only, but you can improve it.

**Comment by kiwisky** [comment]
The issue about UnicodeDecodeError I posted is because there are some non-print chars at row 168, col 84, the end of row 177, 188 and 190.
Now everything is OK. Thank you very much.

**Comment by kiwisky** [comment]
BTW, the non-print chars are in file data\klg\life.yml.

**Comment by uncle-mark** [comment]
Hi Pal,
    Thanks for your reply. I have launched a new version and fixed this bugs.
